sonar.projectKey=janardhanhere_lg-deploy
sonar.organization=janardhanhere

sonar.sources=src/lg_deploy
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8

# Additional Python settings
sonar.python.version=3.11
